Style fix: font style changes now cleaner
Font style is now selected for the whole cover pages at once.
Exception: the fond needs to be re-applied locally for titleFr and titleEr (back cover page), because they rely on the \section* command